Mango.Web/Controllers/AuthController.cs
using Mango.Web.Models;
using Mango.Web.Service;
using Mango.Web.Service.IService;
using Mango.Web.Utility;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace Mango.Web.Controllers
{
	public class AuthController : Controller
	{
		private readonly IAuthService _authService;
        private readonly ITokenProvider _tokenProvider;
        public AuthController(IAuthService authService, ITokenProvider tokenProvider)
        {
            _authService = authService;
            _tokenProvider = tokenProvider; 

        }

        public IActionResult Login()
		{
			LoginRequestDto loginRequestDto = new();
			return View(loginRequestDto);
		}
		
        [HttpPost]
		public async Task<IActionResult> Login(LoginRequestDto obj)
		{
			
			ResponseDto? response = await _authService.LoginAsync(obj);

			if (response != null && response.IsSuccess)
			{
                LoginResponseDto loginResponseDto = JsonConvert.DeserializeObject<LoginResponseDto>(Convert.ToString(response.Result));

                await SignInUser(loginResponseDto);

                _tokenProvider.SetToken(loginResponseDto.Token);

                return RedirectToAction("Index","Home");
			}
            else
            {
                ModelState.AddModelError("CustomError",response.Message);
                return View(obj);
            }

            
		}

        public IActionResult Register()
        {
            var roleList = new List<SelectListItem>()
            {
                new SelectListItem{Text=SD.RoleAdmin,Value=SD.RoleAdmin},
                new SelectListItem{Text=SD.RoleCustomer,Value=SD.RoleCustomer }
            };

            ViewBag.roleList = roleList;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegistrationRequestDto obj)
        {
            ResponseDto result= await _authService.RegisterAsync(obj);
            ResponseDto assingRole;
            if(result!=null && result.IsSuccess)
            {
                if (string.IsNullOrEmpty(obj.Role)){
                    obj.Role = SD.RoleCustomer;
                }
                assingRole = await _authService.AssignRoleAsync(obj);
                if (assingRole != null && assingRole.IsSuccess)
                {
                    return RedirectToAction(nameof(Login));
                }
            }

            var roleList = new List<SelectListItem>()
            {
                new SelectListItem{Text=SD.RoleAdmin,Value=SD.RoleAdmin},
                new SelectListItem{Text=SD.RoleCustomer,Value=SD.RoleCustomer }
            };

            ViewBag.roleList = roleList;

            return View(obj);
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            _tokenProvider.ClearToken();
            return RedirectToAction("Index", "Home");
        }

        private async Task SignInUser(LoginResponseDto model)
        {
            var handler = new JwtSecurityTokenHandler();

            var jwt=handler.ReadJwtToken(model.Token);

            var identity=new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Email, 
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Name).Value));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Sub,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Sub).Value));

            identity.AddClaim(new Claim(ClaimTypes.Name,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));
            identity.AddClaim(new Claim(ClaimTypes.Role,
                jwt.Claims.FirstOrDefault(u => u.Type == "role").Value));


            var principal = new ClaimsPrincipal(identity);
            
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,principal);
        }
    }
}

Mango.Web/Controllers/CouponController.cs
using Mango.Web.Models;
using Mango.Web.Service.IService;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Mango.Web.Controllers
{
    public class CouponController : Controller
    {
        private readonly ICouponService _couponService;
        public CouponController(ICouponService couponService)
        {
            _couponService = couponService;
        }
        public async Task<IActionResult> CouponIndex()
        {
            List<CouponDto>? list = new();

            ResponseDto? response = await _couponService.GetAllCouponAsync();

            if(response != null && response.IsSuccess) 
            {
                list = JsonConvert.DeserializeObject<List<CouponDto>>(Convert.ToString(response.Result));
            }

            return View(list);
        }

        public async Task<IActionResult> CouponCreate()
        {
            return View();
        }

        [HttpPost]
		public async Task<IActionResult> CouponCreate(CouponDto couponDto)
		{
            if (ModelState.IsValid)
            {
			    ResponseDto response = await _couponService.CreateCouponAsync(couponDto);

                if(response.IsSuccess)
                {
                    return RedirectToAction("CouponIndex"); 
                }
            }
			return View(couponDto);
		}

   
        public async Task<IActionResult> CouponDelete(int CouponId)
        {
            
            ResponseDto response = await _couponService.DeleteCouponAsync(CouponId);
            if (response.IsSuccess)
            {
                return RedirectToAction("CouponIndex");
                //add toastr
            }
			
			return RedirectToAction("CouponIndex");

		}
	}
}

Mango.Web/Controllers/ProductController.cs
using Mango.Web.Models;
using Mango.Web.Service.IService;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Mango.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }
        public async Task<IActionResult> ProductIndex()
        {
            List<ProductDto>? list = new();

            ResponseDto? response = await _productService.GetAllProductAsync();

            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<ProductDto>>(Convert.ToString(response.Result));
            }

            return View(list);
        }

        public async Task<IActionResult> ProductCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ProductCreate(ProductDto productDto)
        {
            if (ModelState.IsValid)
            {
                ResponseDto response = await _productService.CreateProductAsync(productDto);

                if (response.IsSuccess)
                {
                    return RedirectToAction("ProductIndex");
                }
            }
            return View(productDto);
        }


        public async Task<IActionResult> ProductDelete(int ProductId)
        {

            ResponseDto response = await _productService.DeleteProductAsync(ProductId);
            if (response.IsSuccess)
            {
                return RedirectToAction("ProductIndex");
                //add toastr
            }

            return RedirectToAction("ProductIndex");

        }
    }
}

Mango.Web/Controllers/ShoppingCartController.cs
using Mango.Web.Models;
using Mango.Web.Models.Dto;
using Mango.Web.Service.IService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;

namespace Mango.Web.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IShoppingCartService _shoppingCartService;
        private readonly IOrderService _orderService;
        public ShoppingCartController(IShoppingCartService shoppingCart, IOrderService orderService)
        {
            _shoppingCartService = shoppingCart;
            _orderService = orderService;

        }
        [Authorize]
        public async Task<IActionResult> ShoppingCartIndex()
        {
            return View(await LoadCartDtoBasedOnLoggedInUserAsync());
        }

        [Authorize]
        public async Task<IActionResult> Checkout()
        {
            return View(await LoadCartDtoBasedOnLoggedInUserAsync());
        }
        [HttpPost]
        [ActionName("Checkout")]
        public async Task<IActionResult> Checkout(CartDto cartDto)
        {

            CartDto cart = await LoadCartDtoBasedOnLoggedInUserAsync();
            cart.CartHeader.Phone = cartDto.CartHeader.Phone;
            cart.CartHeader.Email = cartDto.CartHeader.Email;
            cart.CartHeader.FirstName = cartDto.CartHeader.FirstName;

            var response = await _orderService.CreateOrderAsync(cart);
            OrderHeaderDto orderHeaderDto = JsonConvert.DeserializeObject<OrderHeaderDto>(Convert.ToString(response.Result));

            if (response != null && response.IsSuccess)
            {
                //get stripe session and redirect to stripe to place order
                //
                var domain = Request.Scheme + "://" + Request.Host.Value + "/";

                StripeRequestDto stripeRequestDto = new()
                {
                    ApprovedUrl = domain + "cart/Confirmation?orderId=" + orderHeaderDto.OrderHeaderId,
                    CancelUrl = domain + "cart/checkout",
                    OrderHeader = orderHeaderDto
                };

                var stripeResponse = await _orderService.CreateStripeSessionAsync(stripeRequestDto);
                StripeRequestDto stripeResponseResult = JsonConvert.DeserializeObject<StripeRequestDto>
                                            (Convert.ToString(stripeResponse.Result));
                Response.Headers.Add("Location", stripeResponseResult.StripeSessionUrl);
                return new StatusCodeResult(303);



            }
            return View(cartDto);
        }
        public async Task<IActionResult> Confirmation(int orderId)
        {
            return View(orderId);
        }

        [Authorize]
        public async Task<IActionResult> RemoveFromCart(int detailsId)
        {
            var userId = User.Claims.Where(u => u.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value; 
            ResponseDto? response =await _shoppingCartService.RemoveCartAsync(detailsId);

            return RedirectToAction(nameof(ShoppingCartIndex));
        }
        [Authorize]
        public async Task<IActionResult> ApplyCouponCart(CartDto cartDto)
        {
            ResponseDto response = await _shoppingCartService.ApplyCouponAsync(cartDto);

            if ((bool)response.Result) 
            {
                //toaster message success
                return RedirectToAction(nameof(ShoppingCartIndex));
            }
            //toaster message invalid
            return RedirectToAction(nameof(ShoppingCartIndex));
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EmailCart(CartDto cartDto)
        {

            CartDto cart=await LoadCartDtoBasedOnLoggedInUserAsync();
            cart.CartHeader.Email=User.Claims.Where(u=>u.Type==JwtRegisteredClaimNames.Email)?.FirstOrDefault()?.Value;
            ResponseDto response = await _shoppingCartService.EmailCartAsync(cart);

            if ((bool)response.Result)
            {
                //toaster message success
                return RedirectToAction(nameof(ShoppingCartIndex));
            }
            //toaster message invalid
            return RedirectToAction(nameof(ShoppingCartIndex));
        }
        [Authorize]
        public async Task<IActionResult> RemoveCouponCart(CartDto cartDto)
        {
            ResponseDto response = await _shoppingCartService.RemoveCouponAsync(cartDto);

            if ((bool)response.Result)
            {
                //toaster message success
                return RedirectToAction(nameof(ShoppingCartIndex));
            }
            //toaster message invalid
            return RedirectToAction(nameof(ShoppingCartIndex));
        }



        private async Task<CartDto> LoadCartDtoBasedOnLoggedInUserAsync()
        {
            var userId = User.Claims.Where(u => u.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;
            ResponseDto? response =await _shoppingCartService.GetCartAsync(userId);
            if(response != null && response.IsSuccess) 
            {
                CartDto cartDto=JsonConvert.DeserializeObject<CartDto>(Convert.ToString(response.Result));
                return cartDto;
            }
            return new CartDto();
        }
    }
}

Mango.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mango.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mango.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mango.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Managment
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Coupon" asp-action="CouponIndex">Coupon</a></li>
                                <li><a class="dropdown-item" asp-controller="Product" asp-action="ProductIndex">Product</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-controller="ShoppingCart" asp-action="ShoppingCartIndex">ShoppingCart</a></li>
                            </ul>
                        </li>
                    </ul>
                    @if (!User.Identity.IsAuthenticated) { 
                        <ul>
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        </ul>
                        <ul>
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul>
                            <li class="nav-item">
                                <a class="nav-link " href="#" >@User.Identity.Name</a>
                            </li>
                        </ul>
                        <ul>
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Mango.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>